apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: pdp-dev
  labels:
    tier: airflow
type: Opaque
data:
  fernet-key: "Vms1cGRYcHhRa3hqY2pOVVVtcFdabUUxWWpNNVlWTkxabUp0TW5WeVVIbz0="