apiVersion: v1
kind: Secret
metadata:
  name: airflow-broker-url
  namespace: pdp-dev
  labels:
    tier: airflow
    component: redis
type: Opaque
data:
  connection: "cmVkaXM6Ly86WDlHRXBnelRLTEBhaXJmbG93LXJlZGlzOjYzNzkvMA=="