apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres-creds
  namespace: pdp-dev # Assuming the same namespace as other components
type: Opaque
data:
  # The password "airflow_pass" needs to be base64 encoded.
  # echo -n "airflow_pass" | base64
  # airflow_pass -> YWlyZmxvd19wYXNz
  postgres_password: YWlyZmxvd19wYXNz
