# Source: airflow/templates/secrets/webserver-secret-key-secret.yaml
############################################
## Airflow Webserver Flask Secret Key Secret
############################################

apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: pdp-dev
  labels:
    tier: airflow
    component: webserver
type: Opaque
data:
  webserver-secret-key: "UVdKRFRHRllUM015UmxsaWJGWkZOV3RPUkZJeVMwVk1Xa0pKZURodFFXcz0="